services:
  - type: web
    name: pneumonia-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run App/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TF_NUM_INTEROP_THREADS
        value: 1
      - key: TF_NUM_INTRAOP_THREADS
        value: 1
      - key: TF_ENABLE_ONEDNN_OPTS
        value: 0
